Revert 57572 - Remove the default argument from RegKey::Open.
Caused a failure on Windows Chromium Builder (dbg):

...\configuration_policy_provider_win.cc(71) :
error C2660: 'RegKey::Open' : function does not take
2 arguments

BUG=44644
TEST=base_unittests --gtest_filter=RegistryTest.*

Review URL: http://codereview.chromium.org/3205007

TBR=tfarina@chromium.org
Review URL: http://codereview.chromium.org/3211004

git-svn-id: http://src.chromium.org/svn/trunk/src@57575 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: d187d7c64a7f0817d86c0820f25646f42c1e3ece