Fix chrome build inside the Chromium OS build chroot.
In the chroot used for building Chromium OS, gnome-keyring
is not installed so the gyp fails with the errors like:

Exception: Call to 'pkg-config --cflags gnome-keyring-1' returned exit status 1. while loading dependencies of src/base/base.gyp while loading dependencies of src/net/net.gyp while loading dependencies of src/app/app.gyp while loading dependencies of src/build/all.gyp while trying to load src/build/all.gyp
failed to run command: /usr/bin/python src/build/gyp_chromium

BUG=chromium-os:4000
TEST=Tested on Ubuntu and in the chroot:
On Ubuntu:
  % sudo apt-get remove libgnome-keyring-dev
  % GYP_DEFINES="chromeos=0" gclient runhooks'
  ... gyp fails as libgnome-keyring-dev is not installed ...
  % GYP_DEFINES="chromeos=1" gclient runhooks'
  ... gyp succeeds ...

In the chromium os build chroot:
  % emerge-x86-generic chromeos-chrome
  ... gyp suceeds ...

Review URL: http://codereview.chromium.org/2729010

git-svn-id: http://src.chromium.org/svn/trunk/src@49373 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: f5d1919c1e06784286d10033bd99117cf888782f