file_util.h won't compile if UNIT_TEST and OS_WIN are defined.
src\base/file_util.h(524) : error C2664: 'GetNamedSecurityInfoW' : cannot convert parameter 1 from 'const wchar_t *' to 'LPWSTR'

BUG=none
TEST=none

Review URL: http://codereview.chromium.org/1582040

git-svn-id: http://src.chromium.org/svn/trunk/src@45142 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: ef4595db10d7bbacdcc1d55b3d36603f73b1a8a9