Revert 57572 - Remove the default argument from RegKey::Open.
Caused a failure on Windows Chromium Builder (dbg):

...\configuration_policy_provider_win.cc(71) :
error C2660: 'RegKey::Open' : function does not take
2 arguments

BUG=44644
TEST=base_unittests --gtest_filter=RegistryTest.*

Review URL: http://codereview.chromium.org/3205007

TBR=tfarina@chromium.org
Review URL: http://codereview.chromium.org/3211004

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@57575 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 33c97fcf2dd7aec2d15f6fbca25ad6b5133f154d