Fix Mac Breakpad glue compilation error:
breakpad_mac.mm:137: error: 'parsed_command_line' was not declared in this scope

since r31143

BUG=none
TEST=Breakpad-enabled build should, um, build
Review URL: http://codereview.chromium.org/374011

git-svn-id: http://src.chromium.org/svn/trunk/src@31246 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: e9eb4d3d518611bb95bbc64bea3a1720a6572e7b