Fix chrome build inside the Chromium OS build chroot.
In the chroot used for building Chromium OS, gnome-keyring
is not installed so the gyp fails with the errors like:

Exception: Call to 'pkg-config --cflags gnome-keyring-1' returned exit status 1. while loading dependencies of src/base/base.gyp while loading dependencies of src/net/net.gyp while loading dependencies of src/app/app.gyp while loading dependencies of src/build/all.gyp while trying to load src/build/all.gyp
failed to run command: /usr/bin/python src/build/gyp_chromium

BUG=chromium-os:4000
TEST=Tested on Ubuntu and in the chroot:
On Ubuntu:
  % sudo apt-get remove libgnome-keyring-dev
  % GYP_DEFINES="chromeos=0" gclient runhooks'
  ... gyp fails as libgnome-keyring-dev is not installed ...
  % GYP_DEFINES="chromeos=1" gclient runhooks'
  ... gyp succeeds ...

In the chromium os build chroot:
  % emerge-x86-generic chromeos-chrome
  ... gyp suceeds ...

Review URL: http://codereview.chromium.org/2729010

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@49373 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 7dfe6858e90ee508b99bd71f9bf12e9a353709c7