Fixing compilation error on Linux with GCC 4.3.3. My environment is Ubuntu 9.04 (x86, 32bit).
% hammer --mode=Release
...
Compiling /home/yusukes/chromium2/src/sconsbuild/Release/obj/courgette/adjustment_method_2.o
Linking /home/yusukes/chromium2/src/sconsbuild/Release/startup_tests
cc1plus: warnings being treated as errors
/home/yusukes/chromium2/src/courgette/adjustment_method_2.cc: In constructor 'courgette::adjustment_method_2::ShinglePattern::Index::Index(const courgette::adjustment_method_2::Shingle*)':
/home/yusukes/chromium2/src/courgette/adjustment_method_2.cc:676: error: 'kind' may be used uninitialized in this function
/home/yusukes/chromium2/src/courgette/adjustment_method_2.cc: In constructor 'courgette::adjustment_method_2::ShinglePattern::Index::Index(const courgette::adjustment_method_2::Shingle*)':
/home/yusukes/chromium2/src/courgette/adjustment_method_2.cc:676: error: 'kind' may be used uninitialized in this function
scons: *** [/home/yusukes/chromium2/src/sconsbuild/Release/obj/courgette/adjustment_method_2.o] Error 1
scons: building terminated because of errors

BUG=none
TEST=none

Review URL: http://codereview.chromium.org/159054

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@21062 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: fa67f1e190dd14ebfdf94a3e999989ac9b731b09