Revert "Changed crash opt-in option label to "Help make Google Chrome OS better..." on ChromeOS."
Broke compile on Windows:

first_run_search_engine_view.cc
C:\b\slave\chromium-rel-builder\build\src\build\Release\obj\global_intermediate\chrome\grit/google_chrome_strings.h(53) : error C2220: warning treated as error - no 'object' file generated
C:\b\slave\chromium-rel-builder\build\src\build\Release\obj\global_intermediate\chrome\grit/google_chrome_strings.h(53) : warning C4005: 'IDS_OPTIONS_ENABLE_LOGGING' : macro redefinition
    C:\b\slave\chromium-rel-builder\build\src\build\Release\obj\global_intermediate\chrome\grit/chromium_strings.h(55) : see previous definition of 'IDS_OPTIONS_ENABLE_LOGGING'
C:\b\slave\chromium-rel-builder\build\src\build\Release\obj\global_intermediate\chrome\grit/google_chrome_strings.h(54) : warning C4005: 'IDS_OPTIONS_RESET_MESSAGE' : macro redefinition
    C:\b\slave\chromium-rel-builder\build\src\build\Release\obj\global_intermediate\chrome\grit/chromium_strings.h(53) : see previous definition of 'IDS_OPTIONS_RESET_MESSAGE'
C:\b\slave\chromium-rel-builder\build\src\build\Release\obj\global_intermediate\chrome\grit/google_chrome_strings.h(55) : warning C4005: 'IDS_CANT_WRITE_USER_DIRECTORY_SUMMARY' : macro redefinition
    C:\b\slave\chromium-rel-builder\build\src\build\Release\obj\global_intermediate\chrome\grit/chromium_strings.h(54) : see previous definition of 'IDS_CANT_WRITE_USER_DIRECTORY_SUMMARY'

TBR=zelidrag

Review URL: http://codereview.chromium.org/3111007

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@56251 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 83a9e78aa88b844b9dfc8f5922c5025a6fb9963d