Revert 53892 - Initial scriptable object implementation.
Broke ChromiumOS ARM build, reverting. Errors from log:
remoting/client/plugin/chromoting_scriptable_object.cc: In member function 'virtual bool remoting::ChromotingScriptableObject::HasProperty(const pp::Var&, pp::Var*)':
remoting/client/plugin/chromoting_scriptable_object.cc:48: error: NULL used in arithmetic
remoting/client/plugin/chromoting_scriptable_object.cc: In member function 'virtual bool remoting::ChromotingScriptableObject::HasMethod(const pp::Var&, pp::Var*)':
remoting/client/plugin/chromoting_scriptable_object.cc:63: error: NULL used in arithmetic

BUG=50248
TEST=write javascript to manually setup connection.

Review URL: http://codereview.chromium.org/3064009

TBR=ajwong@chromium.org
Review URL: http://codereview.chromium.org/3020038

git-svn-id: http://src.chromium.org/svn/trunk/src@53949 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: a5d3f01ad6255bdd9fff39403ffa5b94b2c5d91d