Mark URLRequestTestFTP.FTPGetTestAnonymous as flaky.
It failed here:
http://codf2.jail:8010/builders/Modules%20XP/builds/22848/steps/net_unittests/logs/stdio
[ RUN      ] URLRequestTestFTP.FTPGetTestAnonymous
.\url_request\url_request_unittest.cc(2094): error: Value of: static_cast<int>(file_size)
  Actual: 1563
  Expected: d.bytes_received()
  Which is: 0
[  FAILED  ] URLRequestTestFTP.FTPGetTestAnonymous (15 ms)

It passed in the next (forced) build here:
http://codf2.jail:8010/builders/Modules%20XP/builds/22849/steps/net_unittests/logs/stdio
[ RUN      ] URLRequestTestFTP.FTPGetTestAnonymous
[       OK ] URLRequestTestFTP.FTPGetTestAnonymous (16 ms)

BUG=25045
TEST=test is greener than before
TBR=phajdan.jr@chromium.org

Review URL: http://codereview.chromium.org/561062

git-svn-id: http://src.chromium.org/svn/trunk/src@38047 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: 7e5d5a674ddc89a4d905fb5e1bc88c51995a4049