Fix error when manually running http_server on Windows.
This bug was shaken out by Mac changes in r3095.

$ third_party/python_24/python webkit/tools/layout_tests/layout_package/http_server.py --server start
<snip>
ImportError: No module named layout_package.path_utils

Review URL: http://codereview.chromium.org/7095

git-svn-id: http://src.chromium.org/svn/trunk/src@3257 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: 14ce7d2900a83b02a8f592d10b1578595c52a64d