Fix Clang warning about self assignment.
Explicitly cast the variable to void rather than assign to self
to avoid warnings about unused variables.

This fixes the following Clang warning:

webkit/tools/test_shell/test_shell_main.cc:120:12: error: explicitly assigning a
      variable of type 'bool' to itself [-Wself-assign]
  ux_theme = ux_theme;
  ~~~~~~~~ ^ ~~~~~~~~
1 error generated.

(This is a new warning since Clang r122804.)

BUG=none
TEST=none

Review URL: http://codereview.chromium.org/6005012

git-svn-id: http://src.chromium.org/svn/trunk/src@70492 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: 7153a7f9af7ff75bcff17296ad6f1108f7e09e0a