Revert "Changed crash opt-in option label to "Help make Google Chrome OS better..." on ChromeOS."
Broke compile on Windows:

first_run_search_engine_view.cc
C:\b\slave\chromium-rel-builder\build\src\build\Release\obj\global_intermediate\chrome\grit/google_chrome_strings.h(53) : error C2220: warning treated as error - no 'object' file generated
C:\b\slave\chromium-rel-builder\build\src\build\Release\obj\global_intermediate\chrome\grit/google_chrome_strings.h(53) : warning C4005: 'IDS_OPTIONS_ENABLE_LOGGING' : macro redefinition
    C:\b\slave\chromium-rel-builder\build\src\build\Release\obj\global_intermediate\chrome\grit/chromium_strings.h(55) : see previous definition of 'IDS_OPTIONS_ENABLE_LOGGING'
C:\b\slave\chromium-rel-builder\build\src\build\Release\obj\global_intermediate\chrome\grit/google_chrome_strings.h(54) : warning C4005: 'IDS_OPTIONS_RESET_MESSAGE' : macro redefinition
    C:\b\slave\chromium-rel-builder\build\src\build\Release\obj\global_intermediate\chrome\grit/chromium_strings.h(53) : see previous definition of 'IDS_OPTIONS_RESET_MESSAGE'
C:\b\slave\chromium-rel-builder\build\src\build\Release\obj\global_intermediate\chrome\grit/google_chrome_strings.h(55) : warning C4005: 'IDS_CANT_WRITE_USER_DIRECTORY_SUMMARY' : macro redefinition
    C:\b\slave\chromium-rel-builder\build\src\build\Release\obj\global_intermediate\chrome\grit/chromium_strings.h(54) : see previous definition of 'IDS_CANT_WRITE_USER_DIRECTORY_SUMMARY'

TBR=zelidrag

Review URL: http://codereview.chromium.org/3111007

git-svn-id: http://src.chromium.org/svn/trunk/src@56251 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: 75bae0d505d24a5db6f0f17fc5a6c69a5628bdb0