Revert "Fix favorite and auto_connect property usage."
This reverts commit f8650d16d451c5c0e34c8541d598e4e1d0fbbdf8 [formerly 2a5da02ef3fec8da1f223dd1990fb0b56d617188] / r66253:

Fix favorite and auto_connect property usage. BUG=chromium-os:8913 TEST=manually open chrome://settings/internet and see if remembered networks are listed properly. For DOMUI network menu, pass --enable-domui-menu for chrome to enable and check. Review URL: http://codereview.chromium.org/4818002

It broke the ChromeOS and arm compiles with:

chrome/browser/chromeos/options/wifi_config_view_browsertest.cc:44: error: ‘class chromeos::WifiNetwork’ has no member named ‘set_favorite’

TBR=kochi

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@66258 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 70e4660709f53c38d51eef13474434bca248c76f