Revert "net: add Snap Start tests"
This reverts commit r65714. It broke the Linux shared library builders:

SOLINK(target) out/Debug/obj.target/net/libnet_base.so
/usr/bin/ld: error: out/Debug/obj.target/openssl/third_party/openssl/openssl/crypto/sha/sha512t.o: multiple definition of 'main'
/usr/bin/ld: out/Debug/obj.target/openssl/third_party/openssl/openssl/crypto/sha/sha256t.o: previous definition here

git-svn-id: http://src.chromium.org/svn/trunk/src@65715 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: 96a93fd1edb869e42cc0204c9c99636783ca4e86