Linux: use -fno-strict-aliasing when compiling unit_tests with gcc 4.4.
This is needed to squash an aliasing error in stl_tree.h

cc1plus: warnings being treated as errors
./chrome/common/mru_cache.h: In member function ‘virtual void MRUCacheTest_Basic_Test::TestBody()’:
./chrome/common/mru_cache.h:98: error: dereferencing pointer ‘<anonymous>’ does break strict-aliasing rules
/usr/lib/gcc/i386-redhat-linux/4.4.0/../../../../include/c++/4.4.0/bits/stl_tree.h:184: note: initialized from here
make: *** [out/Release/obj.target/unit_tests/chrome/common/mru_cache_unittest.o] Error 1

Bug 27030 has been filed to sort this out properly.

Review URL: http://codereview.chromium.org/346040

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@31420 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: d184a8075bdaef18011c00e00e01c1dba93a3124