Protect header that requires SSE2 on gcc4.4 and remove unused header.
This fixes a compile error on the new 32-bit Lucid buildbots:

In file included from net/tools/flip_server/balsa_headers.cc:7:
/usr/lib/gcc/i486-linux-gnu/4.4.3/include/emmintrin.h:32:3: error: #error "SSE2 instruction set not enabled"
In file included from net/tools/flip_server/balsa_frame.cc:8:
/usr/lib/gcc/i486-linux-gnu/4.4.3/include/emmintrin.h:32:3: error: #error "SSE2 instruction set not enabled"

BUG=
TEST=Lucid builbot compiles

Review URL: http://codereview.chromium.org/6677116

git-svn-id: http://src.chromium.org/svn/trunk/src@80292 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: d96d50993353254446cd527eb4b59ff9e84d525e