Reverting r9823 (http://codereview.chromium.org/16207) because
1) the Interactive Tests (dbg) buildbot needs the SSL cert installed

2) the same buildbot showed a refcounting problem, e.g. 
FATAL:ref_counted.cc(22)] Check failed: in_dtor_. RefCounted object deleted without calling Release()
c:\b\slave\chromium-dbg-builder\build\src\chrome\browser\views\find_bar_win_interactive_uitest.cc(57): error: Value of: NULL != server.get()
  Actual: false
Expected: true
[  FAILED  ] FindInPageTest.CrashEscHandlers (2109 ms)

3) the Webkit Linux buildbot failed four tests
 redirect302-frames.html cross-frame-access-protocol-explicit-domain.html
 cross-frame-access-protocol.html origin-header-for-https.html

I'm leaving the tcp_pinger files in for the moment, they shouldn't hurt anything.

Review URL: http://codereview.chromium.org/23028

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@9827 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: c07d4945731c473a844a80377fc7749aad7c93d3