base: Move CaseInsensitiveCompare traits into the base namespace.
This should fix conflicts like:
2>d:\src\chromium_src2\src\base/string_util.h(480) : error C2904: 'CaseInsensitiveCompare' : name already used for a template in the current scope
2>        d:\src\chromium_src2\src\third_party\xulrunner-sdk\win\include\xpcom\nsStringAPI.h(1406) : see declaration of 'CaseInsensitiveCompare'

Reported-by: Jeff Timanus <twiz@google.com>

BUG=None
TEST=trybots

Review URL: http://codereview.chromium.org/4366001

git-svn-id: http://src.chromium.org/svn/trunk/src@64877 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: c4f423556aa17240edec2848f202f9591d4ae439