Disable ICOImageDecoderTest.ChunkedDecoding since it is failing for no appearent reason.
[ RUN      ] ICOImageDecoderTest.ChunkedDecoding
C:\b\slave\chromium-rel-xp\build\src\webkit\tools\test_shell\image_decoder_unittest.cc(158): error: Expected: (static_cast<WebCore::RGBA32Buffer*>(0)) != (decoder->frameBufferAtIndex(0)), actual: (null) vs (null)
C:\b\slave\chromium-rel-xp\build\src\webkit\data\ico_decoder\1bit.ico
[  FAILED  ] ICOImageDecoderTest.ChunkedDecoding (16 ms)

BUG=19263
TEST=none
TBR=hbono
Review URL: http://codereview.chromium.org/165458

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@23310 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 76584c45711a09f5137a6465b68ab5e460d193ad