Fixing compilation error on Linux with GCC 4.3.3. My environment is Ubuntu 9.04 (x86, 32bit).
% hammer --mode=Release
...
Compiling /home/yusukes/chromium2/src/sconsbuild/Release/obj/courgette/adjustment_method_2.o
Linking /home/yusukes/chromium2/src/sconsbuild/Release/startup_tests
cc1plus: warnings being treated as errors
/home/yusukes/chromium2/src/courgette/adjustment_method_2.cc: In constructor 'courgette::adjustment_method_2::ShinglePattern::Index::Index(const courgette::adjustment_method_2::Shingle*)':
/home/yusukes/chromium2/src/courgette/adjustment_method_2.cc:676: error: 'kind' may be used uninitialized in this function
/home/yusukes/chromium2/src/courgette/adjustment_method_2.cc: In constructor 'courgette::adjustment_method_2::ShinglePattern::Index::Index(const courgette::adjustment_method_2::Shingle*)':
/home/yusukes/chromium2/src/courgette/adjustment_method_2.cc:676: error: 'kind' may be used uninitialized in this function
scons: *** [/home/yusukes/chromium2/src/sconsbuild/Release/obj/courgette/adjustment_method_2.o] Error 1
scons: building terminated because of errors

BUG=none
TEST=none

Review URL: http://codereview.chromium.org/159054

git-svn-id: http://src.chromium.org/svn/trunk/src@21062 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: 41424093dea232cea19d4b19996f55dd0e7284b1