Reverting 7573.
Doing a full build seems always fine. The issue is for incremental builds, it corrupts the PDBs. Errors look like:

glue.lib(autofill_form.obj) : fatal error LNK1318: Unexpected PDB error; RPC (23) '(0x000006BA)'
...\xmemory(155) : error C2471: cannot update program database '...\debug\obj\plugin_tests\vc80.pdb'

We'll probably need to upgrade to VS2008 to add it back.
Review URL: http://codereview.chromium.org/17208

git-svn-id: http://src.chromium.org/svn/trunk/src@7603 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: 765999322642fd3a5cfcd67040de7076268c7003