Revert change 10975 and 10972 because it broke the purify tests, and it might have caused a unit tests failure.
purify error :  UMR in URLRequest::response_data_file
failing test:
URLFetcherHeadersTest.Headers:
c:\b\slave\chromium-rel-builder\build\src\chrome\browser\net\url_fetcher_unittest.cc(222): error: Value of: source->response_headers()->GetNormalizedHeader("cache-control", &header)
  Actual: false
Expected: true
c:\b\slave\chromium-rel-builder\build\src\chrome\browser\net\url_fetcher_unittest.cc(223): error: Value of: header
  Actual: ""
Expected: "private"
c:\b\slave\chromium-rel-builder\build\src\chrome\browser\net\url_fetcher_unittest.cc(181): error: Value of: response_code
  Actual: 404
Expected: 200

Release only.

Review URL: http://codereview.chromium.org/39191

git-svn-id: http://src.chromium.org/svn/trunk/src@10988 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: 70bdfc848daff0c64e8993785bb6227686e91ea7