Move MockLocationProvider to location_provider.cc to fix Linux shared build.
Error was:
out/Release/lib.target/chrome/libbrowser.so: undefined reference to `NewMockLocationProvider()'

MockLocationProvider is used by location_arbitrator.cc resulting in the
above error.

BUG=none
TEST=compiles

Review URL: http://codereview.chromium.org/644002

git-svn-id: http://src.chromium.org/svn/trunk/src@39445 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: d1c632a086ebc80e88e100f75079b21bf1b88c82