Fix some gcc 4.4 issues when compiling with toolkit_views.
Most of these squash harmless compiler warnings but the custom_button.cc
change fixes a real problem with the accelerator key bitmask calculation
(+ preceeds << in terms of operator precedence)

The change to tab_strip.cc is ugly but it fixes the following error:

chrome/browser/views/tabs/tab_strip.cc: In member function
‘void TabStrip::StartRemoveTabAnimation(int, TabContents*)’:
chrome/browser/views/tabs/tab_strip.cc:201: error: assuming
signed overflow does not occur when assuming that
(X - c) > X is always false

As an added bonus, this makes the Linux shared build of toolkit_views
work too.

Review URL: http://codereview.chromium.org/199025

git-svn-id: http://src.chromium.org/svn/trunk/src@25602 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: 94f8719956c4c12d7d065faa414dff9dc351c0df