Revert 73121 - Remove obsolete files from 'sources'.  This causes needless work on incremental builds in VS2010.
This is breaking clobber builds with this error :
e:\b\build\slave\google-chrome-rel-win\build\src\chrome_frame\iids.cc(6) : fatal error C1083: Cannot open include file: 'chrome_tab.h': No such file or directory


BUG=71130
TEST=Check that Chrome builds.

Review URL: http://codereview.chromium.org/6307018

TBR=jeanluc@chromium.org
Review URL: http://codereview.chromium.org/6347032

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@73124 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: ccad6cfb5fb90598dfc11882f78013e377b4eb5f