Fix Clang warning about self assignment.
Explicitly cast the variable to void rather than assign to self
to avoid warnings about unused variables.

This fixes the following Clang warning:

webkit/tools/test_shell/test_shell_main.cc:120:12: error: explicitly assigning a
      variable of type 'bool' to itself [-Wself-assign]
  ux_theme = ux_theme;
  ~~~~~~~~ ^ ~~~~~~~~
1 error generated.

(This is a new warning since Clang r122804.)

BUG=none
TEST=none

Review URL: http://codereview.chromium.org/6005012

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@70492 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: b2ef2dfc1b58cd52fca94274954575de83bf92d9