Revert 73121 - Remove obsolete files from 'sources'.  This causes needless work on incremental builds in VS2010.
This is breaking clobber builds with this error :
e:\b\build\slave\google-chrome-rel-win\build\src\chrome_frame\iids.cc(6) : fatal error C1083: Cannot open include file: 'chrome_tab.h': No such file or directory


BUG=71130
TEST=Check that Chrome builds.

Review URL: http://codereview.chromium.org/6307018

TBR=jeanluc@chromium.org
Review URL: http://codereview.chromium.org/6347032

git-svn-id: http://src.chromium.org/svn/trunk/src@73124 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: cfe1d790587ddd1f955ed6d3f398ab50ed37e47a