Revert "OTS roll (to r49)"
.\src\gdef.cc(353) : error C2220: warning treated as error - no 'object' file
generated
.\src\gdef.cc(353) : warning C4800: 'ots::OpenTypeGDEF *' : forcing value to
bool 'true' or 'false' (performance warning)
Build log was saved at
"file://c:\b\build\slave\cr-win-dbg\build\src\build\Debug\obj\ots\BuildLog.htm"
ots - 1 error(s), 1 warning(s)

This reverts commit 1ff0f52d738c4dbdb1f7ada4936a35e2d1b2266f [formerly cfe9efea7d225e7c5857a57b8991bbd3d82356c9].

BUG=none
TEST=none
TBR=bashi@google.com

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@72949 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: c05a4f3df4fd39a7ad6ac5ad6f5c6f1372df6c80