Disable ICOImageDecoderTest.ChunkedDecoding since it is failing for no appearent reason.
[ RUN      ] ICOImageDecoderTest.ChunkedDecoding
C:\b\slave\chromium-rel-xp\build\src\webkit\tools\test_shell\image_decoder_unittest.cc(158): error: Expected: (static_cast<WebCore::RGBA32Buffer*>(0)) != (decoder->frameBufferAtIndex(0)), actual: (null) vs (null)
C:\b\slave\chromium-rel-xp\build\src\webkit\data\ico_decoder\1bit.ico
[  FAILED  ] ICOImageDecoderTest.ChunkedDecoding (16 ms)

BUG=19263
TEST=none
TBR=hbono
Review URL: http://codereview.chromium.org/165458

git-svn-id: http://src.chromium.org/svn/trunk/src@23310 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: afaa8330771ff0c18b0764bcdbbc52a276232f23