Fix some views errors found by clang (e.g. dead override)
In file included from chrome/browser/ui/views/frame/browser_frame_gtk.cc:13:
./chrome/browser/ui/views/frame/browser_root_view.h:50:31:error: reference to 'OSExchangeData' is ambiguous
  bool GetPasteAndGoURL(const OSExchangeData& data, GURL* url);
                              ^
./chrome/browser/ui/views/frame/browser_root_view.h:12:7: note: candidate found by name lookup is 'OSExchangeData'
class OSExchangeData;
      ^
In file included from chrome/browser/ui/views/frame/browser_frame_gtk.cc:5:
In file included from ./chrome/browser/ui/views/frame/browser_frame_gtk.h:11:
In file included from ./views/window/window_gtk.h:10:
./views/widget/widget_gtk.h:27:11: note: candidate found by name lookup is 'OSExchangeData'
using ui::OSExchangeData;

This is an actual problem because it makes the drag overrides in the class have no effect.

Regressed in http://codereview.chromium.org/6200005

BUG=70465
TEST=none

Review URL: http://codereview.chromium.org/6612027

git-svn-id: http://src.chromium.org/svn/trunk/src@76812 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: 310a2d3e2701603ad0bede2d47d11f8044b3b143