test_support_ui needs to depend on theme_resources to fix this compile issue for clobber build :
Configuration: test_support_ui - Debug|Win32
Compiling...
npapi_test_helper.cc
c:\b\slave\win\build\src\chrome/browser/tab_contents/navigation_entry.h(15) : fatal error C1083: Cannot open include file: 'grit/theme_resources.h': No such file or directory
ui_test.cc


Review URL: http://codereview.chromium.org/131019

git-svn-id: http://src.chromium.org/svn/trunk/src@18686 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: 2b5732b693023d9995e328194704a904abf0130b