Fix PR_ImplodeTime for Linux x64.
This fixes the following error when building for x64 targets:

base/third_party/nspr/prtime.cc: In function 'PRTime PR_ImplodeTime(const 
PRExplodedTime*)':
base/third_party/nspr/prtime.cc:173: error: integer overflow in expression
base/third_party/nspr/prtime.cc:176: error: integer overflow in expression

PRTime is long long (8 bytes) on ia32, and long (8 bytes) on x64.  On ia32,
LONG_MAX (4 bytes) converted to microseconds fits in the PRTime type, but
on x64 LONG_MAX is 8 bytes and so overflows the PRTime type on conversion.

Avoid these issues by only returning INT_MAX.  On ia32 this is the correct
value, and does not change behaviour.  On x64 the call to timegm() will always
succeed due to the increased range of time_t, so the error condition of -1
should never be reached.

Fix a bug in the conditional expression for 1 second before epoch.

Patch by Joel Stanley

Original review URL: http://codereview.chromium.org/160511

R=dean,wtc
BUG=18231
TEST=new unit test
Review URL: http://codereview.chromium.org/164366

git-svn-id: http://src.chromium.org/svn/trunk/src@23186 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: 63ac9a12286235094dfcb45d42606a67439e5bd7