Fix some strict aliasing errors from r31773 caught with gcc 4.4.
I've chosen to use a union here instead of restoring the original memcpy code.

Errors were as follows:

cc1plus: warnings being treated as errors
chrome/browser/safe_browsing/safe_browsing_database_bloom.cc: In member function ‘virtual bool SafeBrowsingDatabaseBloom::ContainsUrl(const GURL&, std::string*, std::vector<int, std::allocator<int> >*, std::vector<SBFullHashResult, std::allocator<SBFullHashResult> >*, base::Time)’:
chrome/browser/safe_browsing/safe_browsing_database_bloom.cc:274: error: dereferencing pointer ‘full_hash.207’ does break strict-aliasing rules
chrome/browser/safe_browsing/safe_browsing_database_bloom.cc:274: note: initialized from here
chrome/browser/safe_browsing/safe_browsing_database_bloom.cc: In member function ‘void SafeBrowsingDatabaseBloom::InsertSub(int, SBPrefix, SBEntry*)’:
chrome/browser/safe_browsing/safe_browsing_database_bloom.cc:478: error: dereferencing pointer ‘full_hash.258’ does break strict-aliasing rules
chrome/browser/safe_browsing/safe_browsing_database_bloom.cc:478: note: initialized from here
chrome/browser/safe_browsing/safe_browsing_database_bloom.cc: In member function ‘void SafeBrowsingDatabaseBloom::InsertAdd(SBPrefix, SBEntry*)’:
chrome/browser/safe_browsing/safe_browsing_database_bloom.cc:402: error: dereferencing pointer ‘full_hash.237’ does break strict-aliasing rules
chrome/browser/safe_browsing/safe_browsing_database_bloom.cc:402: note: initialized from here
make: *** [out/Release/obj.target/browser/chrome/browser/safe_browsing/safe_browsing_database_bloom.o] Error 1

Review URL: http://codereview.chromium.org/389021

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@31798 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 8c722d8f1ce0a056aea2243817571e718acc9170