test_support_ui needs to depend on theme_resources to fix this compile issue for clobber build :
Configuration: test_support_ui - Debug|Win32
Compiling...
npapi_test_helper.cc
c:\b\slave\win\build\src\chrome/browser/tab_contents/navigation_entry.h(15) : fatal error C1083: Cannot open include file: 'grit/theme_resources.h': No such file or directory
ui_test.cc


Review URL: http://codereview.chromium.org/131019

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@18686 0039d316-1c4b-4281-b951-d872f2087c98

Former-commit-id: 0f675c24ba8da6c72be6ef36bef848bd29ab758f