Initialize self._wsout.
If websocket_server.py is called with --server stop, it will call
Stop without calling Start, so it claims as follows:
  AttributeError: 'PyWebSocket' object has no attribute '_wsout'

Review URL: http://codereview.chromium.org/545023

git-svn-id: http://src.chromium.org/svn/trunk/src@35998 4ff67af0-8c30-449e-8e8b-ad334ec8d88c

Former-commit-id: b1e48a04c12731f12fded2a5a64ba286add360a7